#pragma config(Sensor, in1,    mobileBaseLiftPot, sensorPotentiometer)
#pragma config(Sensor, in2,    mainLiftPot,    sensorPotentiometer)
#pragma config(Sensor, in3,    pincerRPot,     sensorPotentiometer)
#pragma config(Sensor, in4,    pincerLPot,     sensorPotentiometer)
#pragma config(Sensor, dgtl1,  leftQuad,       sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  rightQuad,      sensorQuadEncoder)
#pragma config(Motor,  port2,           rightDriveBack, tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           rightDriveFront, tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           leftDriveBack, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           leftDriveFront, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           leftPincer,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           rightPincer,   tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           mobileBaseLift, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          mainLift,      tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// REPO: https://github.com/VTOW/BCI
// DRIVING FUNCTIONS: https://gist.github.com/Octogonapus/c457dc87daadc0557dad5a7e2845710b
// TURNING FUNCTIONS: https://gist.github.com/Octogonapus/2498b09f689599f92713c433c4c112cd

#define BCI_USE_TIMER
#define BCI_USE_POS_PID

#include "C:\Users\Chami\Google Drive\bancroft stuff\11\robotics\2018_InTheZone\inTheZoneLibrary.c";
#include "C:\Users\Chami\Google Drive\bancroft stuff\11\robotics\2018_InTheZone\BCI-master\BCI.h";
#include "C:\Users\Chami\Google Drive\bancroft stuff\11\robotics\2018_InTheZone\BCI-master\drivingFunctions.c";
#include "C:\Users\Chami\Google Drive\bancroft stuff\11\robotics\2018_InTheZone\BCI-master\turningFunctions.c";


task main()
{
	// string side = "";
	//runUserControl();
	driveStraight(100);
}
