#pragma config(Sensor, in1,    mobileBaseLiftPot, sensorPotentiometer)
#pragma config(Sensor, in2,    mainLiftPot,    sensorPotentiometer)
#pragma config(Sensor, in3,    pincerPot,      sensorPotentiometer)
#pragma config(Sensor, dgtl1,  leftQuad,       sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  rightQuad,      sensorQuadEncoder)
#pragma config(Motor,  port1,           rightPincer,   tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           mobileBaseLiftLeft, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           mainLiftLeft,  tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           rightDriveFront, tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           rightDriveBack, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           leftDriveFront, tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           leftDriveBack, tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           mobileBaseLiftRight, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           mainLiftRight, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          leftPincer,    tmotorVex393_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// REPO: https://github.com/VTOW/BCI
// DRIVING FUNCTIONS: https://gist.github.com/Octogonapus/c457dc87daadc0557dad5a7e2845710b
// TURNING FUNCTIONS: https://gist.github.com/Octogonapus/2498b09f689599f92713c433c4c112cd
// Make sure to add these to BCI-master folder

#define BCI_USE_TIMER
#define BCI_USE_POS_PID

#include "C:\Users\Chami\Google Drive\bancroft stuff\11\robotics\2018_InTheZone\InTheZone_2018\2442A_inTheZoneLib.c";
#include "C:\Users\Chami\Google Drive\bancroft stuff\11\robotics\2018_InTheZone\BCI-master\BCI.h";
#include "C:\Users\Chami\Google Drive\bancroft stuff\11\robotics\2018_InTheZone\BCI-master\drivingFunctions.c";
#include "C:\Users\Chami\Google Drive\bancroft stuff\11\robotics\2018_InTheZone\BCI-master\turningFunctions.c";


task main()
{
	//string side = "";
	//driveStraight(2000);
	runUserControl();

}
