#pragma config(Sensor, in1,    mobileBaseLiftPot, sensorPotentiometer)
#pragma config(Sensor, in2,    mainLiftPot,    sensorPotentiometer)
#pragma config(Sensor, in3,    pincerRPot,     sensorPotentiometer)
#pragma config(Sensor, in4,    pincerLPot,     sensorPotentiometer)
#pragma config(Sensor, dgtl1,  leftQuad,       sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  rightQuad,      sensorQuadEncoder)
#pragma config(Motor,  port1,           rightPincer,   tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           mobileBaseLift, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           mainLift,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           rightDriveFront, tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           rightDriveBack, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           leftDriveFront, tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           leftDriveBack, tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port10,          leftPincer,    tmotorVex393_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
Sets left drive motors to a power.
@param leftDrivePower -	a power
*/
void setLeftMotors(int leftDrivePower)
{
	motor[leftDriveBack] = leftDrivePower;
	motor[leftDriveFront] = leftDrivePower;
}
/*
Sets right drive motors to a power.
@param rightDrivePower - a power
*/
void setRightMotors(int rightDrivePower)
{
	motor[rightDriveBack] = rightDrivePower;
	motor[rightDriveFront] = rightDrivePower;
}
/*
Sets both right and left motors to a power
@param drivePower - a power
*/
void setAllDriveMotors(int drivePower)
{
	setLeftMotors(drivePower);
	setRightMotors(drivePower);
}
/*
Sets mobile base lift motor(s) to a power.
@param liftPower - a power.
*/
void setMobileBaseLiftPower(int liftPower)
{
	motor[mobileBaseLift] = liftPower;
}
/*
Sets main lift motor(s) to a power
@param liftPower - a power.
*/
void setMainLiftPower(int liftPower)
{
	motor[mainLift] = liftPower;
}
/*
Sets mobile base lift to a position while proportionally decreasing motor power as lift reaches desired position
@param liftPos - a position
*/
void setMobileBaseLiftToPos(int liftPos)
{
	// from last year: used 0.15 for lift

	// MBL - Mobile Base Lift
	int curr = SensorValue[mobileBaseLiftPot];
	int diff = curr - liftPos;
	int pwr = (int) (0.15 * diff);

	while (abs(pwr) >= 5)
	{
		setMobileBaseLiftPower(pwr);

		// update variables
		curr = SensorValue[mobileBaseLiftPot];
		diff = curr - liftPos;
		pwr = (int) (0.15 * diff);
	}
}
/*
Sets main lift to a position while proportionally decreasing motor power as lift reaches desired position
@param liftPos - a position
*/
void setMainLiftToPos(int liftPos)
{
	// ML - Main Lift
	int curr = SensorValue[mainLiftPot];
	int diff = curr - liftPos;
	int pwr = (int) (0.15 * diff);

	while (abs(pwr) >= 5)
	{
		setMainLiftPower(pwr);

		// update variables
		curr = SensorValue[mainLiftPot];
		diff = curr - liftPos;
		pwr = (int) (0.15 * diff);
	}
}
/*
Sets pincer motor(s) to a power
@param pincerPower - power to set the pincer motors to
*/
void setPincerPower(int pincerPower)
{
	motor[leftPincer] = pincerPower;
	motor[rightPincer] = pincerPower;
}
/*
Sets pincer to a position while decreasing motor power
@param pincerPos - a position
*/
void setPincersToPos(int pincerPos)
{
	// from last year: used 0.25 as the conversion factor for pincers
	int currR = SensorValue[pincerRPot];
	int currL = SensorValue[pincerLPot];
	int diffR = pincerPos - currR;
	int diffL = pincerPos - currL;
	int pwrR = (int) -(0.25 * diffR);
	int pwrL = (int) -(0.25 * diffL);

	while (abs(pwrR) >= 5 || abs(pwrL) >= 5)
	{
		if(abs(pwrR) >= 5)
		{
			motor[rightPincer] = pwrR;
		}

		if(abs(pwrL) >= 5)
		{
			motor[leftPincer] = pwrL;
		}

		currR = SensorValue[pincerRPot];
		currL = SensorValue[pincerLPot];
		diffR = pincerPos - currR;
		diffL = pincerPos - currL;
		pwrR = (int) -(0.25 * diffR);
		pwrL = (int) -(0.25 * diffL);

	}
}
/*
Runs user control
*/
void runUserControl()
{


	while(true)
	{
		// Joysticks
		int  rightJoy = vexRT[Ch2]; // right joystick
		int  leftJoy = vexRT[Ch3]; // left joystick
		// Buttons
		word btn8UP = vexRT[Btn8U]; // button raise mobile base lift
		word btn8DOWN = vexRT[Btn8D]; // button to lower mobile base lift
		// Triggers
		word rightTriggerUP = vexRT[Btn6U]; // trigger to raise main lift
		word rightTriggerDOWN = vexRT[Btn6D]; // trigger to lower main lift
		word leftTriggerUP = vexRT[Btn5U]; // trigger to open pincers
		word leftTriggerDOWN = vexRT[Btn5D]; // trigger to close pincers

		// positions for lift/pincer control
		int posMLU = 0; // main lift up : need value here
		int posMLD = 0; // main lift down : need value here
		int posMBLU = 0; // mobile base lift up : need value here
		int posMBLD = 0; // mobile base lift down : need value here
		int posPinO = 0; // pincer open : need value here
		int posPinC = 0; // pincer closed : need value here

		// Drive Control
		if(leftJoy > 15 || leftJoy < -15) //dead zones
		{
			setLeftMotors(leftJoy);
		}
		else
		{
			setLeftMotors(0);
		}

		if(rightJoy > 15 || rightJoy < -15) //dead zones
		{
			setRightMotors(rightJoy);
		}
		else
		{
			setRightMotors(0);
		}

		/*
		// Mobile base lift control -> change to proportional set...Pos() when ready; use "set..Power" for testing
		if(btn8UP == 1)
		{
		setMobileBaseLiftToPos(posMBLU);
		}
		else if(btn8DOWN == 1)
		{
		setMobileBaseLiftToPos(posMBLD);
		}
		else
		{
		setMobileBaseLiftPower(0);
		}

		// Main lift control -> change to proportional set...Pos() when ready; use "set..Power" for testing

		if(rightTriggerUP == 1)
		{
		setMainLiftToPos(posMLU);
		}
		else if(rightTriggerDOWN == 1)
		{
		setMainLiftToPos(posMLD);
		}
		else
		{
		setMainLiftPower(0);
		}


		// Pincer control -> change to proportional set...Pos() when ready;1 use "set..Power" for testing

		if(leftTriggerUP == 1)
		{
		setPincersToPos(posPinO);
		}
		else if(leftTriggerDOWN == 1)
		{
		setPincerPower(posPinC);
		}
		else
		{
		setPincerPower(0);
		}
		*/
	}
}

/*
Runs programming skills
*/
void runProgrammingSkills()
{
}

/*
Runs autonomous
@param - string side
*/
void runAuton(string side)
{
	// can only start this once we have values for movement

	// - side independent -
	// drive forward for a certain amount
	// reverse for a portion of the forwards movement
	// - side dependent -
	// turn to line up robot w/ scoring zone
	// - side independent -
	// drive forward to move mobile base into scoring zone


}
