#pragma config(Sensor, in1,    liftPoten,      sensorNone)
#pragma config(Sensor, in2,    leftClawPoten,  sensorPotentiometer)
#pragma config(Sensor, in3,    rightClawPoten, sensorPotentiometer)
#pragma config(Sensor, dgtl1,  leftEncoder,    sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  rightEncoder,   sensorQuadEncoder)
#pragma config(Motor,  port1,           rightPincer,   tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           liftRightExtremes, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           liftRightMid,  tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           driveRightFront, tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           driveRightBack, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           driveLeftFront, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           driveLeftBack, tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           liftLeftExtremes, tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           liftLeftMid,   tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port10,          leftPincer,    tmotorVex393_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma systemFile

void setLeftMotors(int power)
{
    motor[driveLeftFront] = power;
    motor[driveLeftBack] = power;
}
void setRightMotors(int power)
{
    motor[driveRightFront] = power;
    motor[driveRightBack] = power;
}
void setAllDriveMotors(int power)
{
		setLeftMotors(power);
		setRightMotors(power);
}

void setLiftPower(int power)
{
    motor[liftLeft] = power;
    motor[liftRight] = power;
}

void setForkliftPower(int power)
{
    //motor[forklift] = power;
		SensorValue[rightPiston] = power;
		SensorValue[leftPiston]  = power;
}

void setClawPower(int power)
{
    motor[claw] = power;
    motor[claw2] = power;
}
